project:
  type: book
  output-dir: docs
  
book:
  title: "Lecture notes for MA52112 (Statistics for Data Science)"
  author: "Karim Anaya-Izquierdo (based on notes by Vangelis Evangelou)"
  date: last-modified
  search: true
  chapters:
    - index.qmd
    - lec01.qmd
  page-navigation: true
  downloads: pdf
  
  
bibliography: 
  - book.bib
  - packages.bib

format:
  html: 
    theme: 
      light: cosmo
      dark: darkly
    cover-image: contractions.jpg
    include-in-header: 
      - mathjax_header.html
    code-link: true
    code-fold: true
    code-copy: true
    code-line-numbers: false
    code-block-bg: true
    code-overflow: scroll
    code-summary: "R Code"
    toc: true
    toc-depth: 3
    embed-resources: true
  pdf: 
    documentclass: scrbook
    keep-tex: true
    include-in-header: preamble.tex
    citation_package: natbib
    code-block-bg: true
    code-line-numbers: true
    urlcolor: blue
    colorlinks: true
  
 



